insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (1, 1, 'Yard Work', 'Luxury', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (2, 2, 'NLTK', 'DS3', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (3, 3, 'Custom CMS Development', 'User Experience', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (4, 4, 'UK Tax', 'Epi Info', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (5, 5, 'Crystal Reports', 'Yachting', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (6, 6, 'Dhcpd', 'Online Gambling', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (7, 7, 'Scientific Writing', 'Mystery Shopping', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (8, 8, 'Eyewear', 'UF/DF', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (9, 9, 'Pro-IV', 'Tiles', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (10, 10, 'Passionate about work', 'IFS', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (11, 11, 'XSS', 'MBD', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (12, 12, 'Negotiation', 'Oncology', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (13, 13, 'Scientific Writing', 'HGV', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (14, 14, 'Healing', 'VST', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (15, 15, 'IGMP', 'Ebooks', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (16, 16, 'VC#', 'Power Generation', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (17, 17, 'Wildlife', 'GPGPU', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (18, 18, 'Egyptology', 'Mac &amp; PC platforms', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (19, 19, 'Long Distance Running', 'DSL', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (20, 20, 'Phase II Subsurface Investigations', 'DDI Certified Facilitator', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (21, 21, 'Avid Newscutter', 'Quality by Design', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (22, 22, 'Document Management', 'Luxury Goods', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (23, 23, 'Help Desk Support', 'Civil Aviation', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (24, 24, 'Hodes IQ', 'Commercial Lending', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (25, 25, 'Databases', 'Tcpdump', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (26, 26, 'Food Quality', 'MCSA + Messaging', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (27, 27, 'XDoclet', 'OSHA 10-Hour', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (28, 28, 'Literature', 'JBoss Seam', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (29, 29, 'UDF', 'MDSD', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (30, 30, 'HP Proliant', 'Bylined Articles', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (31, 31, 'RDBMS', 'RTOS', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (32, 32, 'TCF', 'Radio Broadcasting', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (33, 33, 'Urology', 'QlikView', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (34, 34, 'GSM-R', 'Federal Grants Management', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (35, 35, 'IT Service Delivery', 'GLP', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (36, 36, 'BJJ', 'OLAP', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (37, 37, 'SNOMED', 'IAS 39', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (38, 38, 'Pay TV', 'Chi Nei Tsang', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (39, 39, 'Kickboxing', 'EHR', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (40, 40, 'DLPAR', 'Gemba Kaizen', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (41, 41, 'NSPS', 'Custom CMS Development', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (42, 42, 'OLT', 'Akka', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (43, 43, 'Medical Illustration', 'VTune', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (44, 44, 'RCRA', 'DV', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (45, 45, 'Pro II', 'RPG Free', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (46, 46, 'EEM', 'Business Ideas', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (47, 47, 'DMX', 'nCode', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (48, 48, 'Image Manipulation', 'Yard Signs', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (49, 49, 'HR Project Management', 'PDMLink', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (50, 50, 'MS Integration Services', 'Blue Ocean Strategy', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (51, 1, 'DFSORT', 'MVS', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (52, 2, 'DDS', 'Outdoors', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (53, 3, 'Fortran', 'Luxury', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (54, 4, 'XP/Vista/7', 'DNA methylation', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (55, 5, 'DDL', 'UV', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (56, 6, 'Drywall', 'Woodworking', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (57, 7, 'Jitter', 'Surgery', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (58, 8, 'CA Unicenter NSM', 'WFC', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (59, 9, 'AACR2', 'Tcsh', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (60, 10, 'ML', 'Customer Experience', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (61, 11, 'Snowboarding', 'Adult Education', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (62, 12, 'Dhcpd', 'CSI', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (63, 13, 'QlikView Development', 'HTFS', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (64, 14, 'Class III Medical Devices', 'Cellular Communications', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (65, 15, 'Cisco Routers', 'HP Networking', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (66, 16, 'AJAX Frameworks', 'Navisworks', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (67, 17, 'OMT', 'TPE', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (68, 18, 'Corporate Finance', 'Eggplant', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (69, 19, 'Blood Typing', 'Governance', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (70, 20, 'Sensory Evaluation', 'Zainet', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (71, 21, 'Youth Outreach', 'iHistorian', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (72, 22, 'Updos', 'Hardware Architecture', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (73, 23, 'Signal Processing', 'Usability Testing', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (74, 24, 'OAT', 'VW', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (75, 25, 'DTI', 'Rheumatology', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (76, 26, 'Earthworks', 'Mobile Marketing', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (77, 27, 'Slackware', 'AC Nielsen', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (78, 28, 'SGBD', 'News Writing', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (79, 29, 'RTM', 'Sybase IQ', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (80, 30, 'Legal Liability', 'JMF', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (81, 31, 'X-ray', 'HDI', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (82, 32, 'Dual Diagnosis', 'Foreclosures', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (83, 33, 'Scripting', 'Government Contracting', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (84, 34, 'Ethnography', 'Spring Framework', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (85, 35, 'Microsoft Technologies', 'CCNP', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (86, 36, 'MM7', 'Wrongful Death', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (87, 37, 'Logistics Management', 'Change Orders', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (88, 38, 'CCNA', 'Microsoft DNS', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (89, 39, 'CST Microwave Studio', 'Job Search', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (90, 40, 'Electrical Design', 'CCDP', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (91, 41, 'OA Framework', 'IFR', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (92, 42, 'vRanger', '3D Modeling', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (93, 43, 'Nonprofits', 'Hazardous Materials', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (94, 44, 'RHIT', 'RCS Selector', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (95, 45, 'Document Review', 'Commercial Litigation', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (96, 46, 'Nuclear', 'BTS', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (97, 47, 'RNAi', 'BIM', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (98, 48, 'NCBI', 'Government', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (99, 49, 'Network Security', 'Operational Risk', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (100, 50, 'Sports Play-by-play', 'Critical Care', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (101, 1, 'ILM', 'Occupational Therapy', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (102, 2, 'Ableton Live', 'UTP', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (103, 3, 'PMD', 'Litigation Support', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (104, 4, 'PgSQL', 'TV News Production', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (105, 5, 'RFQ Development', 'Vray', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (106, 6, 'UNIX Utilities', 'Teeth Whitening', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (107, 7, 'Minority Owned', 'E-zines', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (108, 8, 'Water Management', 'VHF', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (109, 9, 'RDCS', 'Canon DSLR', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (110, 10, 'HSM', 'RDC', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (111, 11, 'DSDM', 'Fluid Dynamics', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (112, 12, 'Pharmacy', 'Logistics Management', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (113, 13, 'Airport Management', 'Dubbing', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (114, 14, 'NCLB', 'ArcGIS', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (115, 15, 'Wireframes', 'UML', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (116, 16, 'MDSD', 'EU Funding', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (117, 17, 'TWIC Card', 'Jin Shin Jyutsu', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (118, 18, 'DCF', 'Lines Of Credit', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (119, 19, 'Egyptian Arabic', 'Yield Management', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (120, 20, 'SQL', 'DWR', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (121, 21, 'Real Estate License', 'Utilization', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (122, 22, 'FFA', 'IT Audit', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (123, 23, 'MPIO', 'RMAN', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (124, 24, 'DFMA', 'MW', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (125, 25, 'Google Analytics', 'XRY', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (126, 26, 'Btrieve', 'OEE', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (127, 27, 'WCF Services', 'IFR', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (128, 28, 'American English', 'Prenuptial Agreements', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (129, 29, 'Essential Oils', 'BMP design', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (130, 30, 'LDP', 'Aqualogic', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (131, 31, 'TyMetrix', 'NAS', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (132, 32, 'SWIFT Messaging', 'Hoshin Kanri', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (133, 33, 'FPGA', 'IBM AIX', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (134, 34, 'RFQ', 'RSA SecurID', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (135, 35, 'GSE', 'PBUSE', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (136, 36, 'Kickstart', 'MyEclipse', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (137, 37, 'OEM contracts', 'Koha', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (138, 38, 'IBM iSeries', 'TK Solver', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (139, 39, 'International Business', 'English', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (140, 40, 'RMAN', 'Windows Azure', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (141, 41, 'DBU', 'Virtual DJ', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (142, 42, 'IASO', 'Flatbed', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (143, 43, 'Product Launch', 'Avaya AES', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (144, 44, 'Workplace Violence', 'Therapists', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (145, 45, 'Underground Mining', 'Job Coaching', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (146, 46, 'TFF', 'FxCop', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (147, 47, 'TMAP', 'Piano Education', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (148, 48, 'DDR', 'IQMS', false);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (149, 49, 'Axure RP', 'FTC', true);
insert into skill (id, personal_info_id, skill_title, skill_description, is_public) values (150, 50, 'CDMA2000', 'Utilization', false);